from . import society_setup
from . import society_tower
from . import society_flat
from . import society_committee
from . import resident_registrations
from . import res_users
from . import vehicle_registrations
from . import parking_management
from . import help_desk
from . import society_dashboard
from . import amenity_booking
from . import society_maintenance
from . import society_alert